remote:
  origin:
    url: https://wrgl.llead.co
    fetch:
      - +refs/heads/event:refs/remotes/origin/event
      - +refs/heads/personnel:refs/remotes/origin/personnel
      - +refs/heads/documents:refs/remotes/origin/documents
      - +refs/heads/news_article_classification:refs/remotes/origin/news_article_classification
branch:
  event:
    remote: origin
    merge: refs/heads/event
    file: output/event.csv
    primaryKey:
      - event_uid
  personnel:
    remote: origin
    merge: refs/heads/personnel
    file: output/personnel.csv
    primaryKey:
      - uid
  documents:
    remote: origin
    merge: refs/heads/documents
    file: output/documents.csv
    primaryKey:
      - docid
      - hrg_no
      - matched_uid
      - agency
  news_article_classification:
    remote: origin
    merge: refs/heads/news_article_classification
    file: output/news_article_classification.csv
    primaryKey:
      - article_id
merge:
  fastForward: only
pack:
  maxFileSize: 67108864 # 64Mb
